# tasks file for pycharm
---

- hosts:
    - scratch
  become: yes
  vars:
    pycharm_downloads_path: /var/lib/ansible/pycharm/downloads
    pycharm_download_url: 'http://download.jetbrains.com/python'
    pycharm_edition: community
    pycharm_version: 2020.2.2
    pycharm_install_prefix: /opt

  tasks:
    - name: create (download) directory
      file:
        path: "{{ pycharm_downloads_path }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      tags:
        - configuration
        - pycharm
        - pycharm-download

    - name: download
      get_url:
        url: "{{ pycharm_download_url }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
        dest: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
        owner: root
        group: root
        mode: 0644
      tags:
        - configuration
        - pycharm
        - pycharm-download

    - block:

        - name: install | old
          unarchive:
            src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
            dest: "{{ pycharm_install_prefix }}"
            creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_version }}"
            copy: false
          when: pycharm_version is version('2016.1.0', '<')
          tags:
            - pycharm-install-old

        - name: install | new
          unarchive:
            src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
            dest: "{{ pycharm_install_prefix }}"
            creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}"
            copy: false
          when: pycharm_version is version('2016.1.0', '>=')
          tags:
            - pycharm-install-new

      tags:
        - configuration
        - pycharm
        - pycharm-install